# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_auto_20160825_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
