# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_auto_20160825_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=200)),
                ('power', models.CharField(max_length=200)),
                ('torque', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Brand')),
            ],
        ),
    ]
