# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_carmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='power',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='torque',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='transmission',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='dengine',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='dpower',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='dtorque',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='dtransmission',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='pengine',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='ppower',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='ptorque',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='ptransmission',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='text',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
