# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_auto_20161023_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cname',
            field=models.CharField(default='nil', max_length=200),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='cmodel_name',
            field=models.CharField(default='nil', max_length=200),
        ),
    ]
